#! /usr/bin/bash
read -p "Eneter a valid name for Database to connect " databaseName
validation=$(. validName "$databaseName")
if [[ validation -eq 0 ]] ; then
if [[  -d ./$databaseName ]] ; then
cd ./$databaseName
PS3="$databaseName --> "
select choice in Create List Drop Insert Select Update Delete "Back To Database Menu" Exit
do 
case $choice  in 
Create)
. createTable
;;
List)
ls -F | grep /*.meta -v
;;
Drop)
. dropTable
;;
Insert)
. insertTable
;;
Select)
. selectTable
;;
Update)
. updateTable
;;
Delete)
. DeleteTable
;;
"Back To Database Menu")
cd ../..
. database
;;
Exit)
exit
;;
*)
echo -e "${RED}enter a valid choice${ENDCOLOR}"
;;
esac
done




else 
echo -e "${RED}$databaseName not exists${ENDCOLOR}"
fi
else 
echo -e "${RED}enter a valid name${ENDCOLOR}"
fi
