#! /usr/bin/bash
read -p "Eneter a valid name for Database (No special charchters or white spaces) " databaseName
validation=$(. validName "$databaseName")
if [[ validation -eq 0 ]] ; then
if [[ ! -d ./$databaseName ]] ; then
mkdir ./$databaseName
echo database $databaseName created
else 
echo $databaseName already exist
fi
else 
echo "enter a valid name"
fi