#! /usr/bin/bash
read -p "Eneter a valid name for Database (No special charchters or white spaces) " databaseName
validation=$(. validName "$databaseName")
if [[ $validation -eq 0 ]] ; then
if [[ ! -d ./$databaseName ]] ; then
mkdir ./$databaseName
echo -e "${GREEN}database $databaseName created${ENDCOLOR}"
else 
echo -e "${RED}$databaseName already exist${ENDCOLOR}"
fi
else 
echo -e "${RED}enter a valid name${ENDCOLOR}"
fi