#! /usr/bin/bash

export RED="\e[31m"
export GREEN="\e[32m"
export YELLOW="\e[33m"
export ENDCOLOR="\e[0m"

dbPath=$(pwd)
databaseFolder=$dbPath/DataBase
if [[ ! -d $databaseFolder ]] ; then
mkdir $dbPath/DataBase 
fi
cd $dbPath/DataBase
PS3="DB  >>  "
select choice in Create List Drop Connect Exit
do 
case $choice  in 
Create)
. createDB
;;
List)
ls -F | grep /
;;
Drop)
. dropDB
;;
Connect)
. connectDB
;;
Exit)
exit
;;
*)
echo -e  "${RED}enter a valid choice${ENDCOLOR}"
;;
esac
done
