#! /usr/bin/bash
read -p "enter a valid table name: " table
validation=$(. validName "$table")
if [[ -f $table ]]; then
 PS3="$table -->  "
select choice in byColumnValue allRecords "Back To Connect database" Exit
do 
case $choice  in 
byColumnValue)
read -p "enter a valid column name: " column
validation1=$(. validName "$column")
order=$(awk -F : -v m=$column '{if(m==$1){print NR}}' "$table.meta")
if [[ $order -ne 0 ]]; then
read -p "enter a valid value: " value
deletedRows=$(awk -F : -v v=$value  -v o=$order '{if(v==$o){print NR}}' $table)
rowsNum=0
flag=0
for i in $deletedRows;
do
flag=$(($flag+1))
if [[ $flag -ne 1 ]]; then
i=$(($i-$flag+1))
fi
rowsNum=$(($rowsNum+1))
sed -i "${i}d" $table
done
if [[ $rowsNum -eq 0 ]]; then
    echo 0 rows are affected
else
    echo "$rowsNum rows are affected"
fi
elif [[ $validation1 -eq 1 ]]; then
    echo "column name is invalid (No special charchters or white spa3ces)"
else
    echo "column not exists" 
fi
;;
allRecords)
echo > $table
echo all records have been deleted successfully
;;
"Back To Connect database")
cd ../
. connectDB
;;
Exit)
exit
;;
*)
echo enter a valid choice
;;
esac
done
elif [[ $validation -eq 1 ]]; then
    echo "table name is invalid (No special charchters or white spa3ces)"
else
    echo "table not exists" 
fi