#! /usr/bin/bash
read -p "enter a valid table name: " table
validation=$(. validName "$table")
if [[ -f $table ]]; then
    rm $table
    echo -e "${GREEN}table has been removed successfully${ENDCOLOR}"
elif [[ $validation -eq 1 ]]; then
    echo -e "${RED}table name is invalid (No special charchters or white spaces)${ENDCOLOR}"
else
    echo -e "${RED}table not exists${ENDCOLOR}" 
fi