#! /usr/bin/bash
read -p "Eneter name of data base " databaseName
validation=$(. validName "$databaseName")
if [[ validation -eq 0 ]] ; then
if [[ -d ./$databaseName ]] ; then
rm -r ./$databaseName
echo -e "${GREEN}database $databaseName removed${ENDCOLOR}"
else 
echo -e "${RED}$databaseName not exists${ENDCOLOR}"
fi
else 
echo -e "${RED}enter a valid name${ENDCOLOR}"
fi